services:
  - type: web
    name: dental-crm-client
    env: static
    rootDir: clinic-crm
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
